### PR TITLE
Docs refactor

### PR DESCRIPTION
**Pull request by dev-matan-tsuberi**
This PR refactors the docs in Arc according to the structure specified in [here](https://docs.google.com/document/d/1uKhFAqS85H0XfuMpsWos-KR9Ue3Oy_IoHrpfCjFg5UM)

It also streamlines the docs workflow with a new cli (`yarn docs --help`) that handles all the automation for you.

[See up-to-date docs live + instruction on how to use the cli](https://daostack.github.io/arc/#contributing-to-arc-docs).

(Please confirm everything is working correctly for you by downloading the branch and running the commands.)

### CODE REVIEW

**Comment by leviadam** [comment]
Why does this branch still contains the docs_old?

**Comment by dev-matan-tsuberi** [comment]
deleted `docs_old` here and created a corrosponding PR https://github.com/daostack/docs/pull/2 in `daostack/docs` that adds them there under `old` folder.

**Comment by leviadam** [comment]
Good. Though I don't think they have to be there as well.

**Comment by dev-matan-tsuberi** [comment]
You are welcome to delete anything you think should be deleted in there.

**Pull request merged**
