### PR TITLE
Gas cost measurement (ERC827 vs MiniMe)

### PR DESCRIPTION
**Pull request by dev-matan-tsuberi**
This PR is purely for discussion purposes and not intended to merge into master.

Changes:
- `controller/DAOToken.sol` contains 3 implementations: `DAOTokenERC20`, `DAOTokenERC827` and `DAOTokenMiniMe`.
- `test/gasReport.js` contains a simple script that measures gas costs for each ERC20 method for each implementation and displays them in a nice table. .

results are summarized in the [google doc](https://docs.google.com/document/d/1WqML19pIyNnT4vqnsfD9VkxyjNGB7HLkHSSc9jMKtAY/edit#).
You can reproduce the report with `truffle exec test/gasReport.js`.

Interesting, Turns out `MiniMe`'s transfer **is** more expensive but only a ~50% increase, instead of my predicted 4x increase.

### CODE REVIEW

**Comment by dev-matan-tsuberi** [comment]
[Token transfer and call scheme](https://trello.com/c/TMqBadLF/3-token-transfer-and-call-scheme)

**Comment by Alonski** [comment]
Hey, BTW you added yarn.error to this 😃

**Comment by dev-matan-tsuberi** [comment]
Yeah well it's not going to merge to master. The other PR at the moment fixes this with `.gitignore`.

**Comment by Alonski** [comment]
image

**Comment by leviadam** [comment]
This implementation is problematic.
The minime token is not covering the transfer+data methods of 827.

I say we start with 827, and later maybe add minime.

**Comment by dev-matan-tsuberi** [comment]
You want a fourth implementation inhereting both 827 and minime?

**Comment by leviadam** [comment]
No. I want it removed for now.
The DAOtoken is a standard. We cannot have one which is 827 and the other that is not.
We have to choose.
I say for now we go with 827, and later maybe add minime, but it all must be under a single `DAOtoken` contract. Not creating two standards.

**Comment by dev-matan-tsuberi** [comment]
@leviadam 
of course we're not going to have multiple `DAOToken`s, that was just for test.
I guess it's decided, we go for 827, https://github.com/daostack/arc/pull/389.

**Pull request closed without merging**
