### PR TITLE
extend ERC827 instead of StandardToken

### PR DESCRIPTION
**Pull request by dev-matan-tsuberi**
Increase GAS limit to 6600000
Add more gas to DAOCreatore.forgeOrg
DAOToken is not destructible any more.

### CODE REVIEW

**Comment by orenyodfat** [comment]
Increase GAS limit to 6600000
Add more gas to DAOCreatore.forgeOrg
DAOToken is not destructible any more.

**Comment by Alonski** [comment]
Just wondering. Why was destructable removed?

**Comment by dev-matan-tsuberi** [comment]
[Token transfer and call scheme](https://trello.com/c/TMqBadLF/3-token-transfer-and-call-scheme)

**Comment by dev-matan-tsuberi** [comment]
@Alonski 
Because it's unneeded and because it caused the weird error (god knows why).

**Pull request merged**
