### PR TITLE
docs:update

### PR DESCRIPTION
**Pull request by dev-matan-tsuberi**

### CODE REVIEW

**Comment by leviadam** [comment]
Please remove `yarn-error` and rebase.

**Comment by dev-matan-tsuberi** [comment]
@leviadam 
Update https://github.com/daostack/arc/pull/384/commits/ee174a2d0feeb6a9e4040af0943d60bd63db57a6
+ it also removes `yarn.lock` and `.vscode` dir, which for some reason exist in the repo even though they are in the `.gitignore`

**Comment by leviadam** [comment]
Notice that in general one do have to commit the `yarn-lock`, but since we are now working with `npm` I think it is a good call to remove it.

**Comment by dev-matan-tsuberi** [comment]
Yes, we have `package.lock`.

**Pull request merged**
